"""Add object_key, deleted and deleted_at fields to Photo model

Revision ID: 024db35fbebc
Revises: 
Create Date: 2026-02-02 18:12:53.971775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024db35fbebc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('original_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('original_url')
        batch_op.drop_column('object_key')

    # ### end Alembic commands ###
